// generated by OpenBlock
#include <Arduino.h>
#include <CubeLLM.h>

float session;
float msg1;
float photo1;
CubeLLM cubeLLM;

void setup() {
    Serial.begin(115200);
}

void loop() {
    delay(5*1000);
    cubeLLM.show_alert("hello");
}
